import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import Footer from "@/components/Footer";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "relative")}>
      <DefaultLayout>
        {children}
      </DefaultLayout>
      </body>
    </html>
  );
}

const DefaultLayout = ({children}: {
  children: React.ReactNode;
}) => {

  return(
      <>
        <Navbar/>
        {children}
          <Footer />
      </>
  )
}