import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/NavigationMenu";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DefaultLayout>
        {children}
      </DefaultLayout>
      </body>
    </html>
  );
}

const DefaultLayout = ({children}: {
  children: React.ReactNode;
}) => {

  return(
      <>
        <NavigationMenu/>
        {children}
      </>
  )
}